export const SET_MODAL_INNER_INGREDIENT_DETAILS = "SET_MODAL_INNER_INGREDIENT_DETAILS";
export const SET_MODAL_INNER_ORDER_DETAILS = "SET_MODAL_INNER_ORDER_DETAILS";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";
export const SET_CURRENT_INGREDIENT = "SET_CURRENT_INGREDIENT";
export const SET_MODAL_INNER_ORDER_INFO = "SET_MODAL_INNER_ORDER_INFO";
export const SET_CURRENT_ORDER_INFO = "SET_CURRENT_ORDER_INFO";