
export const SEND_EMAIL_REQUEST: "SEND_EMAIL_REQUEST" = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS: "SEND_EMAIL_SUCCESS" = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILED: "SEND_EMAIL_FAILED" = "SEND_EMAIL_FAILED";

export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = "RESET_PASSWORD_FAILED";

export const SET_EMAILCODE: "SET_EMAILCODE" = "SET_EMAILCODE";
export const RESET_EMAILCODE: "RESET_EMAILCODE" = "RESET_EMAILCODE";

export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const SET_EMAIL: "SET_EMAIL" = "SET_EMAIL";
export const RESET_EMAIL: "RESET_EMAIL" = "RESET_EMAIL";

export const SET_PASSWORD: "SET_PASSWORD" = "SET_PASSWORD";
export const RESET_PASSWORD: "RESET_PASSWORD" = "RESET_PASSWORD";

export const SET_NAME: "SET_NAME" = "SET_NAME";
export const RESET_NAME: "RESET_NAME" = "RESET_NAME"

export const USER_INFO: "USER_INFO" = "USER_INFO";

export const GET_USER_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS" = "GET_ALL_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILED: "GET_ALL_ORDERS_FAILED" = "GET_ALL_ORDERS_FAILED";