export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const ORDER_RESET: "ORDER_RESET" = "ORDER_RESET";

// export const GET_ALL_ORDERS_SUCCESS: "GET_ALL_ORDERS_SUCCESS" = "GET_ALL_ORDERS_SUCCESS";
// export const GET_ALL_ORDERS_FAILED: "GET_ALL_ORDERS_FAILED" = "GET_ALL_ORDERS_FAILED";