export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const SET_EMAIL: "SET_EMAIL" = "SET_EMAIL";
export const RESET_EMAIL: "RESET_EMAIL" = "RESET_EMAIL";

export const SET_PASSWORD: "SET_PASSWORD" = "SET_PASSWORD";
export const RESET_PASSWORD: "RESET_PASSWORD" = "RESET_PASSWORD";

export const SET_NAME: "SET_NAME" = "SET_NAME";
export const RESET_NAME: "RESET_NAME" = "RESET_NAME"

export const USER_INFO: "USER_INFO" = "USER_INFO";