export const USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST" = "USER_LOGIN_REQUEST";
export const USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST" = "USER_LOGOUT_REQUEST";
export const UPDATE_USER_TOKEN_REQUEST: "UPDATE_USER_TOKEN_REQUEST" = "UPDATE_USER_TOKEN_REQUEST";
export const UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST" = "UPDATE_USER_INFO_REQUEST"
export const USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST" = "USER_REGISTER_REQUEST";

export const GET_USER_INFO_REQUEST: "GET_USER_INFO_REQUEST" = "GET_USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS: "GET_USER_INFO_SUCCESS" = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_FAILED: "GET_USER_INFO_FAILED" = "GET_USER_INFO_FAILED";

// export const SET_USER_REQUEST: "SET_USER_REQUEST" = "SET_USER_REQUEST";
// export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
// export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";

export const SET_EMAIL: "SET_EMAIL" = "SET_EMAIL";
export const RESET_EMAIL: "RESET_EMAIL" = "RESET_EMAIL";

export const SET_PASSWORD: "SET_PASSWORD" = "SET_PASSWORD";
export const RESET_PASSWORD: "RESET_PASSWORD" = "RESET_PASSWORD";

export const SET_NAME: "SET_NAME" = "SET_NAME";
export const RESET_NAME: "RESET_NAME" = "RESET_NAME"

export const USER_INFO: "USER_INFO" = "USER_INFO";